#!/bin/bash
#________________________________________
#
#

#
#
#

chef_solo='/opt/chef/bin/chef-solo'

#

instance=${1:-default}
config_rb_path="config/${instance}.rb"
config_json_path="config/${instance}.json"

#

source 'lib/utilities.sh'

#

bootstrap

#

$chef_solo \
  --config $config_rb_path \
  --json-attributes $config_json_path \
  ;
